### ISSUE TITLE
Create working examples from Buck&Hollingsworth paper

### ISSUE THREAD

**Issue by hainest** [dyninst/examples#1]
https://www.dyninst.org/sites/default/files/apiPreprint.pdf

@MandrakeCQC Could you extract the examples from that paper and turn them into working examples- including a sample mutatee for each one, and submit a PR for that? Definitely feel free to work with any of us to get started on the conversions.

**Comment by MandrakeCQC** [comment]
Hello Tim, I am thinking of creating them under the examples repo, could you grant me access to modify it?

**Comment by hainest** [comment]
@MandrakeCQC That was weird. For some reason, you weren't listed as a dev. You should have access now.

**Comment by MandrakeCQC** [comment]
Sorry, I think the issue still persists. I am getting the following error right now:
`(70)$ git remote set-url origin git@github.com:dyninst/examples.git
(71)$ ls
code_patching/  README.md
 (72)$ git symbolic-ref --short HEAD
keren
(73)$ git push origin keren
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(74)$ git remote set-url origin https://github.com/dyninst/examples.git
(75)$ git push origin keren
Username for 'https://github.com': MandrakeCQC
Password for 'https://MandrakeCQC@github.com':
remote: Permission to dyninst/examples.git denied to MandrakeCQC.
fatal: unable to access 'https://github.com/dyninst/examples.git/': The requested URL returned error: 403
`
I am able to create new files but not branches through my browser, and it requires verification to merge https://github.com/dyninst/examples/compare/master...MandrakeCQC:patch-1. I wonder if this suggests anything.
I will just develop locally right now.

**Comment by hainest** [comment]
The site says you haven't accepted the invite to the Dyninst Developers group.
