### ISSUE TITLE
Not able to build CodeCoverage tool

### ISSUE THREAD

**Issue by tosanjay** [dyninst/examples#22]
Hi, 
I am following the instructions given in the README of examples repo. I am trying to build codecoverage example.
I used the following command:
```
$cmake . -DDYNINST_DIR=/tools/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/dyninst-11.0.1-4s4ejzjbibw4vzclube2rxrvusnauuvf/lib/cmake/Dyninst
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sanjay/tools/dyninst-examples/codeCoverage

```
After that I use make command to build, but got the following error. I have set env DYNINST_INCLUDE to point to `/tools/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/dyninst-11.0.1-4s4ejzjbibw4vzclube2rxrvusnauuvf/include`.

```
$ make 
[ 12%] Building CXX object CMakeFiles/code_coverage.dir/code_coverage.C.o
/tools/dyninst-examples/codeCoverage/code_coverage.C:25:10: fatal error: BPatch.h: No such file or directory
 #include "BPatch.h"
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/code_coverage.dir/build.make:75: recipe for target 'CMakeFiles/code_coverage.dir/code_coverage.C.o' failed
make[2]: *** [CMakeFiles/code_coverage.dir/code_coverage.C.o] Error 1
CMakeFiles/Makefile2:89: recipe for target 'CMakeFiles/code_coverage.dir/all' failed
make[1]: *** [CMakeFiles/code_coverage.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

```

Any suggest to debug the issue is appreciated. Note: I am new to Dyninst.

**PS: I think I understood the problem. I used spack to install dyninst, which in turn installed the dependencies separately, including boost, tbb etc. As a result, build is failing. So, time to explore spack first!**

**Comment by tosanjay** [comment]
So far, this is what worked for me: Setting the CXXFLAGS with paths to all -I and -L works well.

**Comment by hainest** [comment]
@tosanjay I didn't realize there were still old build instructions in the subdirectories. I'll fix that! You should configure from the root directory and then say `make codeCoverage` to build just that one. For example,

    $ git clone https://github.com/dyninst/examples.git
    $ cd examples
    $ mkdir build; cd $_
    $ cmake .. -DDyninst_DIR=path/to/Dyninst/install/lib/cmake/Dyninst
    $ make codeCoverage
