### ISSUE TITLE
Unable to build examples

### ISSUE THREAD

**Issue by jordialcaraz** [dyninst/examples#43]
I have done:
$ git clone https://github.com/dyninst/examples.git
$ cd examples
$ mkdir build; cd build
$ cmake .. -DDyninst_DIR=/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.4.0/dyninst-12.3.0-5ftrzgmjylyj6lbcrzfmqom4pnldwdki/lib/cmake/Dyninst

But cmake reports this error:

`CMake Error at CFGraph/CMakeLists.txt:3 (add_executable):
  Target "CFGraph" links to target "Dyninst::dyninstAPI" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?`
  
  Any ideas of why this could happen?
  
  I installed dyninst with spack (spack install dyninst; spack load dyninst).
  
  Thanks

**Comment by hainest** [comment]
The updated CMake targets are only available in the latest development version of Dyninst. `spack install dyninst@master` will get you there. Let us know if you run into any other troubles!

**Comment by jordialcaraz** [comment]
Thanks, this worked.
